### ISSUE TITLE
CORS middleware: response.addHeaders() not always available

### ISSUE THREAD

**Issue by grob** [ringo/stick#44]
Stick's mount middleware returns a [plain JS response object](https://github.com/ringo/stick/blob/master/lib/middleware/mount.js#L116-120) in case of a missing trailing slash. The current CORS middleware however [relies](https://github.com/ringo/stick/blob/master/lib/middleware/cors.js#L62 et.al.) on the response object's method `.addHeaders()`, which leads to an exception. This also happens if using `.redirect()` or `.notModified()` of the standard RingoJS jsgi utility module, see ringo/ringojs#257.

Probably the easiest fix would be to modify stick to utilize the RingoJS response utility module (there's also a `redirectTo()` helper method that would need to change). Otoh it would make sense avoid `.addHeaders()` calls, as this won't force applications to use the response util module.

**Comment by botic** [comment]
Fixed in 739632a9aadbdeab4d0819482ed7513852b60365
