### ISSUE TITLE
CORS middleware should handle OPTIONS requests

### ISSUE THREAD

**Issue by oberhamsi** [ringo/stick#46]
it has all the info it needs to provide the right response and it's its job to deal with CORS to avoid repeating the same code in the views.

if an application really wants to see the OPTIONS request, we could add a `forwardOptions` option to the middleware.

**Comment by botic** [comment]
Is this still an issue or a wontfix, @oberhamsi?

**Comment by oberhamsi** [comment]
this looks great. lots of useful new features.

i don't understand why vary isn't sent if it's a wildcard origin, here: https://github.com/ringo/stick/blob/6b431fc8fb380660b24c41ee01d0939d55b6786a/lib/middleware/cors.js#L136 shouldn't vary:Origin be set whenever the request can also be CORS

**Comment by botic** [comment]
The idea is, that responses with `*` should be cacheable not regarding the origin of the request. If you access an URL from `Origin: https://example.com` and later from `Origin: https://foo.bar`, it should be the same response not varying based on the sent origin header.
