### ISSUE TITLE
etag middleware kills website if larger than 30kb

### ISSUE THREAD

**Issue by botic** [ringo/stick#53]
I enabled the etag middleware for https://data.seestadt.city and it stopped the response after ~ 30kb.

**Comment by grob** [comment]
That's strange: i'm using the etag middleware in an application that frequently responds with several hundred kB of JSON, and i never experienced anything like this (using both master of ringojs (3d377) and stick (f8f088)). Did you get an exception, or did the response just stop?

**Comment by botic** [comment]
Just stopping in the middle of the request, nothing in the logs, no exceptions so far. I'm trying to debug the thing later today.

**Comment by botic** [comment]
The root issue is the gzip middleware.

```javascript
// works
app.configure("notfound", "gzip", "etag", "static");

// invalid content length
app.configure("notfound", "etag", "gzip", "static");
```

Maybe we can prevent such an error in the future by telling the etag middleware about gzip?
